main_module/urls.py
from django.contrib import admin
from django.urls import path
from main_module import views
from main_module.views_pkg import (IndexView,AboutView,
                                   HomeView,DashboardView,
                                   HeatMapView,Risk,RiskCategory,
                                   Risk,Issue)
from main_module.views_pkg.apis import (risk_data,riskcategory_map_data)

from django.conf.urls import url


urlpatterns = [
    #api_urls
    path('risk_data/', risk_data.risk_data,name='risk_data'),
    path('riskcategory_map_data/', riskcategory_map_data.riskcategory_map_data,name='riskcategory_map_data'),

    path('about/', AboutView.AboutView.as_view(),name='about'),
    #path('home/', HomeView.HomeView.as_view(),name='dash'),
    path('indexv/', IndexView.IndexView.as_view(),name='indexv'),
    path('home/', DashboardView.DashboardView.as_view(),name='home'),
    path('', DashboardView.DashboardView.as_view(),name='home'),
    path('heat_map/', HeatMapView.HeatMapView.as_view(),name='heat_map'),
    #path('', IndexView.IndexView.as_view(), name='welcomepage'),



    #Risk
    path('risk_list', DashboardView.DashboardView.as_view(),name='risk_list'),
    path('riskdrafts', Risk.DraftRiskListView.as_view(), name='risk_draft_list'),
    url(r'^risk/(?P<pk>[-\w]+)/$', Risk.RiskDetailView.as_view(),name="risk_detail"),
    path('risk_add/', Risk.RiskCreateView.as_view(),name="risk_add"),
    url(r'^risk/update/(?P<pk>[-\w]+)/$', Risk.RiskUpdateView.as_view(),name="risk_update"),
    url(r'^risk/del/(?P<pk>[-\w]+)/$', Risk.RiskDeleteView.as_view(),name="risk_del"),
    #RiskCategory
    path('riskcategory_map/', RiskCategory.RiskCategoryMapView.as_view(),name='riskcategory_map'),
    path('riskcategory_list', RiskCategory.RiskCategoryListView.as_view(), name='riskcategory_list'),
    url(r'^riskcategory/(?P<pk>[-\w]+)/$', RiskCategory.RiskCategoryDetailView.as_view(),name="riskcategory_detail"),
    path('riskcategory_add/', RiskCategory.RiskCategoryCreateView.as_view(),name="riskcategory_add"),
    url(r'^riskcategory/update/(?P<pk>[-\w]+)/$', RiskCategory.RiskCategoryUpdateView.as_view(),name="riskcategory_update"),
    url(r'^riskcategory/del/(?P<pk>[-\w]+)/$', RiskCategory.RiskCategoryDeleteView.as_view(),name="riskcategory_del"),
    #Issue
    path('issue_list', Issue.IssueListView.as_view(), name='issue_list'),
    url(r'^issue/(?P<pk>[-\w]+)/$', Issue.IssueDetailView.as_view(),name="issue_detail"),
    path('issue_add/', Issue.IssueCreateView.as_view(),name="issue_add"),
    url(r'^issue/update/(?P<pk>[-\w]+)/$', Issue.IssueUpdateView.as_view(),name="issue_update"),
    url(r'^issue/del/(?P<pk>[-\w]+)/$', Issue.IssueDeleteView.as_view(),name="issue_del"),

]

riskmgmt/urls.py
from django.contrib import admin
from django.urls import path, include
from main_module.views_pkg import (IndexView)
from main_module.views_pkg.func_view import (register,)
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main_module/', include('main_module.urls')),
    path('', IndexView.IndexView.as_view(), name='index'),
    path('welcome', IndexView.IndexView.as_view(), name='welcomepage'),
    url(r'^register/$',register.register,name="register"),
    url(r'^signup/$',register.register,name="signup"),
    url(r'^logout/$',auth_views.LogoutView.as_view(template_name="registeration/logout.html"),
        name="logout"),
    url(r'^login/$',auth_views.LoginView.as_view(template_name="registeration/login.html",
                                                 redirect_field_name="main_module/home"),
        name="login"),
]

main_module/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User



# Create your models here.
class Organization(models.Model):
    name= models.CharField(max_length=1024)
    ris_appetite= models.TextField(blank=True)
    ris_tolerance= models.TextField(blank=True)
    def __str__(self):
        return self.name

class UserProfileInfo(models.Model):
    user =models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio=models.URLField(blank=True)
    picture=models.ImageField(upload_to="profile_pics",blank=True)
    organization = models.ForeignKey(Organization,blank=True,null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class RiskCategory(models.Model):
    category_title = models.CharField(max_length=1024)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='children',on_delete=models.CASCADE)
    level=models.IntegerField(default=0)
    description = models.TextField(blank=True)
    hierarcy=models.CharField(default='',blank=True, max_length=1024)

    type_of_category_dic =(
        ("0", "Pure Risk"),
        ("1", "Speculative Risk"),

    )
    type_of_category = models.CharField(default=0,max_length=1, choices=type_of_category_dic)
    color=models.CharField(max_length=10,default='#FFFFFF', blank=True,null=True)


    def get_parent_color(self):
        a=self.hierarcy.split('-')
        if len(a)<=1 :
            return self.color
        else:

            return RiskCategory.objects.filter(hierarcy__exact=a[0])[0].color
    def save(self, *args, **kwargs):
        super(RiskCategory, self).save(*args, **kwargs)
        if str(self.parent) == "None":
            self.level=0
            self.hierarcy=str(self.pk)
        else:
            self.level=self.parent.level+1
            self.hierarcy=str(self.parent.pk)+"-"+str(self.pk)
        super(RiskCategory, self).save(*args, **kwargs)
    def get_absolute_url(self):
        return reverse('riskcategory_detail',kwargs={'pk':self.pk})
    def __str__(self):
        if self.type_of_category == "0":
            e='P'
        else:
            e='S'

        if str(self.parent) == "None":
            s=''
        else:
            s=str(self.parent)+": "
        return s+str(self.category_title)#+"("+e+")"

class Risk(models.Model):
    title = models.CharField(max_length=1024)
    category = models.ForeignKey(RiskCategory,on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    user_register = models.ForeignKey(User,on_delete=models.CASCADE)
    create_date = models.DateField(default=timezone.now)
    impact = models.IntegerField(default=0)
    likelihood = models.IntegerField(default=0)

    #Criticality: a product of the risk priority number elements
    #of consequence and occurance used to determine the relative
    #risk of a failure mode and effects analysis item
    criticality = models.IntegerField(blank=True,null=True)

    #rate the severity of the effect of the failure
    #consequence = models.IntegerField(blank=True,null=True)
    #rate the likelihood that a failure will occur (failure rate)
    #occurance = models.IntegerField(blank=True,null=True)
    #rate the likelihood that the failure will not be detected before it reaches the customer
    #detection = models.IntegerField(blank=True,null=True)

    is_active = models.BooleanField(default=False)
    def update_criticality(self):
        self.criticality = self.impact * self.likelihood
        self.save()
    def apprived_documents(self):
        return self.risk_documents.filter(is_active=True)
    def get_absolute_url(self):
        return reverse('risk_detail',kwargs={'pk':self.pk})
    def activate_risk(self):
        self.is_active=True
        self.save()
    def __str__(self):
        return self.title

class RiskResiduals(models.Model):
    risk = models.ForeignKey(Risk,on_delete=models.CASCADE,related_name='source_risk')
    resulted_risk = models.ForeignKey(Risk,on_delete=models.CASCADE,related_name='result_risk')
    def __str__(self):
        return self.risk.title+"->"+self.resulted_risk.title
# define class for Issues, Incidents, Losses, actions, IssueLog, IncidentLog, Losslog
class Issue(models.Model):
    title = models.CharField(max_length=1024)
    description = models.TextField(blank=True)
    issue = models.ForeignKey('self', blank=True, null=True, related_name='children',on_delete=models.CASCADE)
    level=models.IntegerField(default=0)
    hierarcy=models.CharField(default='',blank=True, max_length=1024)
    def get_absolute_url(self):
        return reverse('issue_detail',kwargs={'pk':self.pk})
    def save(self, *args, **kwargs):
        if str(self.issue) == "None":
            self.level=0
            self.hierarcy='0'
        else:
            self.level=self.issue.level+1
            self.hierarcy=self.issue.hierarcy+"-"+str(self.level)
        super(Issue, self).save(*args, **kwargs)
    def __str__(self):
        return self.title
# class IssueRegister(models.Model):
#     issue = models.ForeignKey(Issue,on_delete=models.CASCADE,related_name='issue_register_rel')
#     occurance_date = models.DateTimeField()
#     description = models.TextField(blank=True)
#     def __str__(self):
#         return self.title
# class Incident(models.Model):
#     title = models.CharField(max_length=1024)
#     description = models.TextField(blank=True)
#     def __str__(self):
#         return self.title
# class IncidentIssues(models.Model):
#     incident = models.ForeignKey(Incident,on_delete=models.CASCADE,related_name='cause_incident')
#     issue = models.ForeignKey(Issue,on_delete=models.CASCADE,related_name='source_issue')
#     def __str__(self):
#         return self.issue.title+"->"+self.incident.title
# class Loss(models.Model):
#     title = models.CharField(max_length=1024)
#     description = models.TextField(blank=True)
#     def __str__(self):
#         return self.title
# class LossIncident(models.Model):
#     loss = models.ForeignKey(Loss,on_delete=models.CASCADE,related_name='cause_loss')
#     incident = models.ForeignKey(Incident,on_delete=models.CASCADE,related_name='source_incident')
#     def __str__(self):
#         return self.incident.title+"->"+self.loss.title

class Document(models.Model):
    title = models.CharField(max_length=1024)
    description = models.TextField(blank=True)
    upload_date = models.DateField(default=timezone.now)
    file_type =(
        ("P", "PDF File"),
        ("D", "Document File Doc"),
        ("x", "Excel File XLS"),
    )
    type = models.CharField(max_length=1, choices=file_type)
    uploader_user = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    file=models.FileField(upload_to="documents_files",blank=True)
    risk = models.ForeignKey(Risk,related_name="risk_documents",on_delete=models.CASCADE)

    is_active=models.BooleanField(default=False)

    def activate_document(self):
        self.is_active=True
        self.save()

    def get_absolute_url(self):
        return reverse('risk_list')
    def __str__(self):
        return str(self.type)+":"+self.title

main_module/models/Organization.py
from django.db import models
class Organization(models.Model):
    name= models.CharField(max_length=1024)
    ris_appetite= models.TextField(blank=True)
    ris_tolerance= models.TextField(blank=True)
    def __str__(self):
        return self.name

main_module/forms.py
from django import forms
from django.contrib.auth.models import User
from main_module.models import (Risk,Document,
                                RiskCategory,Issue,
                                UserProfileInfo)
class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User

        fields=('username','email','password')

class ProfileUserInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio','picture')

class IssueForm(forms.ModelForm):
    class Meta():
        model = Issue
        fields=('title','issue',
                'description')



        widgets = {
            'title':forms.TextInput(attrs={'class':"form-control mr-sm-2",'placeholder':'Enter the title of risk category.'}),
            'issue':forms.Select(attrs={'class':"form-control mr-sm-2"}),
            'description':forms.Textarea(attrs={'class':'form-control editable medium-editor-textarea postcontent'}),
            #'level':forms.TextInput(attrs={'class':"form-control mr-sm-2"}),
            #'hierarcy':forms.TextInput(attrs={'class':"form-control mr-sm-2"}),
            #'color':forms.TextInput(attrs={'class':"form-control mr-sm-2"}),
            #'type_of_category':forms.Select(attrs={'class':"form-control mr-sm-2"}),

        }
class RiskCategoryForm(forms.ModelForm):
    class Meta():
        model = RiskCategory
        fields=('category_title','parent',
                'description','type_of_category','color')
        widgets = {
            'category_title':forms.TextInput(attrs={'class':"form-control mr-sm-2",'placeholder':'Enter the title of risk category.'}),
            'parent':forms.Select(attrs={'class':"form-control mr-sm-2"}),
            'description':forms.Textarea(attrs={'class':'form-control editable medium-editor-textarea postcontent'}),
            #'level':forms.TextInput(attrs={'class':"form-control mr-sm-2"}),
            #'hierarcy':forms.TextInput(attrs={'class':"form-control mr-sm-2"}),
            'color':forms.TextInput(attrs={'class':"form-control mr-sm-2"}),
            'type_of_category':forms.Select(attrs={'class':"form-control mr-sm-2"}),

        }



class RiskForm(forms.ModelForm):
    class Meta():
        model = Risk
        fields=('title','description','category','user_register','create_date','impact','likelihood',
                #'criticality',
                'is_active')

        widgets = {
            'title':forms.TextInput(attrs={'class':"form-control mr-sm-2",'placeholder':'Enter the title of risk.'}),
            'description':forms.Textarea(attrs={
                'class':"textarea",'id':"description", 'placeholder':"Place some text here",
                'style':'"width: 100%; height: 400px; font-size: 14px; line-height: 18px;border: 1px solid #dddddd; padding: 10px;"'}),
            'create_date': forms.TextInput(attrs={'class':"form-control datetimepicker-input",'id':'reservationdate',
                                                   'data-target':'reservationdate','data-toggle':"datetimepicker",
                                                   'data-target':"#reservationdate"}),
            'impact':forms.TextInput(attrs={'id':"range_5", 'name':"range_5", 'value':"0;10",
                'class':"form-control mr-sm-2"}),
            'likelihood':forms.TextInput(attrs={'id':"range_4", 'name':"range_4", 'value':"0;10",
                'class':"form-control mr-sm-2"}),
            #'criticality':forms.TextInput(attrs={'class':"form-control mr-sm-2"}),
            'user_register':forms.Select(attrs={'class':"form-control mr-sm-2"}),
            'category':forms.Select(attrs={'style':'"width: 100%;"',
                'class':"form-control mr-sm-2 select2"}),
            'is_active':forms.CheckboxInput(attrs={'id':"customSwitch1",
                'class':"form-control mr-sm-2"}),
        }
class DocumentForm(forms.ModelForm):
    class Meta():
        model = Document
        fields=('title','description')

main_module/views.py
from main_module.models import RiskCategory
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse








@login_required()
def get_auto_complete_description(request):
    description = str(request.POST.get('description', None))
    data = RiskCategory.objects.filter(category_title__icontains=description)[:10]
    res = []
    for d in data:
        res.append(d.category_title)
    return JsonResponse({'description': res})

main_module/templates/main_module/base.html
    <!DOCTYPE html>
    {% load static %}
    <html lang="en" dir="ltr">
       <head>
          <meta charset="utf-8">
          <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
          <link rel='stylesheet' href="{% static 'css/bootstrap.min.css' %}">
          <script src="{% static 'js/bootstrap.min.js' %}"></script>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

          <title></title>
       </head>
       <body>
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
             <a class="navbar-brand" href="#">
                <div class="Container">
                   <img src="{% static welcomePages.logo_url %}" height="50px" alt="">
                </div>
             </a>
             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
             </button>
             <div class="collapse navbar-collapse" id="navbarNavDropdown">

                <ul class="navbar-nav  mr-auto">
                   <li class="nav-item active">
                      <a class="nav-link" href="{% url 'about' %}">
                        Welcome </a>
                   </li>
                   <li class="nav-item dropdown">
                <a class="nav-link nav-item-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkri" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Risk Identification
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkri">
                    <a class="nav-link dropdown-item" href="{% url 'risk_list' %}">Risk Register</a>
                    <a class="nav-link dropdown-item" href="{% url 'heat_map' %}">Heat Map</a>


                </div>
            </li>
<li class="nav-item dropdown">
            <a class="nav-link nav-item-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkran" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                Risk Analysis
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkran">
                <a class="nav-link dropdown-item" href="{% url 'risk_list' %}">Risk Register</a>
                <a class="nav-link dropdown-item" href="/ballast/upload/new/">New</a>

            </div>
        </li>
<li class="nav-item dropdown">
        <a class="nav-link nav-item-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkrt" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
            Risk Treatments
        </a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkrt">
            <a class="nav-link dropdown-item" href="{% url 'risk_list' %}">Risk Register</a>
            <a class="nav-link dropdown-item" href="/ballast/upload/new/">New</a>

        </div>
    </li>
    <li class="nav-item dropdown">
    <a class="nav-link nav-item-link dropdown-toggle" href="#" id="navbarDropdownMenuLinkrm" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">
        Risk Monitoring
    </a>

    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkrm">
        <a class="nav-link dropdown-item" href="{% url 'risk_list' %}">Risk Register</a>
        <a class="nav-link dropdown-item" href="/ballast/upload/new/">New</a>

    </div>
</li>

            <li class="nav-item dropdown">
            <a class="nav-link nav-item-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
             Configurations
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
             <a class="nav-link dropdown-item" href="{% url 'riskcategory_list' %}">Risk Categories</a>
             <a class="nav-link dropdown-item" href="{% url 'riskcategory_map' %}">Risk Category Map</a>

            </div>
            </li>


            <li class="nav-item dropdown">
            <a class="nav-link nav-item-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
             Tools
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
             <a class="nav-link dropdown-item" href="{% url 'issue_list' %}">Issues</a>
             <a class="nav-link dropdown-item" href="{% url 'issue_list' %}">Issues Log</a>
             <a class="nav-link dropdown-item" href="{% url 'riskcategory_map' %}">Incidents</a>
             <a class="nav-link dropdown-item" href="{% url 'riskcategory_map' %}">Losses</a>

            </div>
            </li>


             <li class="nav-item active">
             <a class="nav-link" href="{% url 'risk_list' %}">Documents</a>
           </li>






                </ul>


                   {% if user.is_authenticated %}
                   <ul class="navbar-nav">
                   <li class="nav-link float-right"><a  href="{% url 'logout' %}"  class="btn btn-outline-secondary" role="button" aria-pressed="true">{{ user }} logout</a></li>
                   </ul>
                   {% else %}
                   <ul class="nav navbar-nav float-right">
                   <li class="nav-link float-right"><a  href="{% url 'login' %}" class="btn btn-outline-secondary" role="button" aria-pressed="true">login</a></li>
                   </ul>



                   {% endif %}

             </div>
          </nav>
          <div class="Container" style="background:url('{% static welcomePages.backgroungimg_url %}'); no-repeat center center fixed;
             -webkit-background-size: cover;
             -moz-background-size: cover;
             -o-background-size: cover;
             background-size: cover;">
             <div class="Container">
                {% block body_block %}
                {% endblock %}
             </div>
             <div class="Container">
                <!-- Footer -->
                <footer class="page-footer font-small blue">
                   <!-- Copyright -->
                   <div class="footer-copyright text-center py-3">© 2020 Copyright:
                      <a href="https://web.cs.dal.ca/~etemad"> {{ welcomePages.title  }}</a>
                   </div>
                   <!-- Copyright -->
                </footer>
                <!-- Footer -->
             </div>
          </div>
          <script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
});
</script>
       </body>
    </html>

main_module/templates/main_module/home.html
<!DOCTYPE html>
{% extends "main_module/base.html" %}
{% load static %}
{% block body_block %}

{% endblock %}

main_module/templates/main_module/issue_confirm_delete.html
<!DOCTYPE html>
{% extends "main_module/base.html" %}
{% load static %}
{% block body_block %}
<div class="jumbotron" style="
   width: 80%;
   margin-left: auto;margin-right: auto; margin-bottom:10px">
   <h4>Delete {{ riskcategory}} </h4>
<form method="post">
  {% csrf_token %}
  <input type="Submit" class="btn btn-danger" value="Delete">
  <a class="btn btn-primary" href="{% url 'issue_list' %}">cancel</a>

</form>
</div>
{% endblock %}

main_module/templates/main_module/issue_form.html
<!DOCTYPE html>
{% extends "main_module/base.html" %}
{% load static %}
{% block body_block %}
<div class="jumbotron" style="
   width: 80%;
   margin-left: auto;margin-right: auto; margin-bottom:10px">
   <h4>
   {% if not form.instance.pk %}
   New Issue
   {% else %}
   Update issue Profile
   {% endif %}
   </h4>
   <form class=""  method="post">
     {% csrf_token %}
     {{ form.as_p }}
     <input type="submit" class="btn btn-primary" value="Submit">
     <a class="btn btn-danger" href="{% url 'issue_list' %}"><i class="	fa fa-close"></i></a>

   </form>

</div>

{% endblock %}

main_module/templates/main_module/risk_confirm_delete.html
<!DOCTYPE html>
{% extends "main_module/base.html" %}
{% load static %}
{% block body_block %}
<div class="jumbotron" style="
   width: 80%;
   margin-left: auto;margin-right: auto; margin-bottom:10px">
   <h4>Delete {{ education.title}} </h4>
<form method="post">
  {% csrf_token %}
  <input type="Submit" class="btn btn-danger" value="Delete">
  <a class="btn btn-primary" href="{% url 'risk_list' %}">cancel</a>

</form>
</div>
{% endblock %}

main_module/templates/main_module/risk_detail.html
<!DOCTYPE html>
{% extends "main_module/base.html" %}
{% load static %}
{% block body_block %}
<div class="jumbotron" style="
   width: 80%;
   margin-left: auto;margin-right: auto; margin-bottom:10px">
   <h4>Risk </h4>
   <h5>{{risk_detail.title}}</h5>
   <h5>{{risk_detail.type}}</h5>
   <h5>{{risk_detail.user_register}}</h5>
   <h5>{{risk_detail.create_date}}</h5>
   <h5>{{risk_detail.impact}}</h5>

      <div class="card-body">
               {{risk_detail.description|safe}}
   </div>
   <a class="btn btn-danger" href="{% url 'risk_list' %}"><i class="	fa fa-close"></i></a>
</div>
{% endblock %}

main_module/templates/main_module/riskcategory_list.html
<!DOCTYPE html>
{% extends "main_module/base_dash.html" %}
{% load static %}
{% load my_tag %}
{% block body_block %}



   <div class="card">
     <div class="card-header"><h5 class="float-left">Risk Categories</h5>
   {% if user.is_authenticated and perms.main_module.add_riskcategory %}
   <a  data-toggle="tooltip" data-placement="left" title="Register new risk categories here."
    class="btn btn-primary float-right" href="{% url 'riskcategory_add' %}">
     <i class="fa fa-plus"></i></a>
   {% endif %}
     </div>
     <div class="card-body">
<table class="table table-sm table-light">
  <thead>
    <tr>

      <th scope="col">Code</th>
      <th scope="col">Category Title</th>

    </tr>
  </thead>
  <tbody>
    {% for el in RiskCategoryList %}
    <tr>

      <td style="background-color:  {{ el|get_parent_color }}" width="50px">

    </td>
      <td >
        {% if user.is_authenticated and perms.main_module.view_riskcategory %}
        <a data-toggle="tooltip" data-placement="top" title="Click here to see details."
        class="nav-link float-left" href="{% url 'riskcategory_detail' pk=el.pk %}"
        class="card-link">{{el}}</a>
        {% else %}
        <p class="float-left">{{el}} </p>
        {% endif %}



      {% if user.is_authenticated and  perms.main_module.delete_riskcategory %}
      <a  data-toggle="tooltip" data-placement="right" title="Click here to remove this risk category."
      class="btn btn-danger float-right" href="{% url 'riskcategory_del' pk=el.pk %}">
      <i class="	fa fa-close"></i></a>
      {% endif %}
      {% if user.is_authenticated and  perms.main_module.change_riskcategory %}
      <a  data-toggle="tooltip" data-placement="left" title="Click here to edit this risk category."
      class="btn btn-warning float-right" href="{% url 'riskcategory_update' pk=el.pk %}">
      <i class="fa fa-edit"></i></a>
      {% endif %}
      {% if el.type_of_category == "0" %}
  <span class="badge badge-primary float-right">Pure</span>
  {% endif %}
  {% if el.type_of_category == "1" %}
  <span class="badge badge-success float-right">Speculative</span>
  {% endif %}
    </tr>
    {% endfor %}
    </td>




  </tbody>
</table>


  </div>
  <div class="card-footer">

      <div class="pagination">
        <center>
          <span class="step-links">
              {% if page_obj.has_previous %}
                  <a class="btn btn-primary" href="?page=1"> first </a>
                  <a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}"> previous </a>
              {% endif %}

              <span class="current">
                   {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
              </span>

              {% if page_obj.has_next %}
                  <a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}"> next </a>
                  <a class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}"> last </a>
              {% endif %}
          </span>
          </center>
      </div>

      </div>
</div>
{% endblock %}